from datetime import datetime
from typing import Any, Literal, Protocol

from dooers.protocol.models import Run, Thread, ThreadEvent

EventOrder = Literal["asc", "desc"]

FILTERABLE_FIELDS = {"type", "actor", "user_id", "user_name", "user_email", "run_id"}


class Persistence(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def migrate(self) -> None: ...
    async def create_thread(self, thread: Thread) -> None: ...
    async def get_thread(self, thread_id: str) -> Thread | None: ...
    async def update_thread(self, thread: Thread) -> None: ...
    async def list_threads(
        self,
        worker_id: str,
        organization_id: str,
        workspace_id: str,
        user_id: str | None,
        cursor: str | None,
        limit: int,
    ) -> list[Thread]: ...
    async def delete_thread(self, thread_id: str) -> None: ...
    async def create_event(self, event: ThreadEvent) -> None: ...
    async def get_events(
        self,
        thread_id: str,
        *,
        after_event_id: str | None = None,
        limit: int = 50,
        order: EventOrder = "asc",
        filters: dict[str, str] | None = None,
    ) -> list[ThreadEvent]: ...
    async def create_run(self, run: Run) -> None: ...
    async def update_run(self, run: Run) -> None: ...

    async def get_settings(self, worker_id: str) -> dict[str, Any]: ...
    async def update_setting(self, worker_id: str, field_id: str, value: Any) -> datetime: ...
    async def set_settings(self, worker_id: str, values: dict[str, Any]) -> datetime: ...
