from datetime import datetime
from typing import Any, Protocol

from dooers.protocol.models import Run, Thread, ThreadEvent


class Persistence(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def migrate(self) -> None: ...
    async def create_thread(self, thread: Thread) -> None: ...
    async def get_thread(self, thread_id: str) -> Thread | None: ...
    async def update_thread(self, thread: Thread) -> None: ...
    async def list_threads(
        self,
        worker_id: str,
        user_id: str | None,
        cursor: str | None,
        limit: int,
    ) -> list[Thread]: ...
    async def create_event(self, event: ThreadEvent) -> None: ...
    async def get_events(
        self,
        thread_id: str,
        after_event_id: str | None,
        limit: int,
    ) -> list[ThreadEvent]: ...
    async def create_run(self, run: Run) -> None: ...
    async def update_run(self, run: Run) -> None: ...

    # Settings methods
    async def get_settings(self, worker_id: str) -> dict[str, Any]:
        """Get all stored values for a worker. Returns empty dict if none."""
        ...

    async def update_setting(self, worker_id: str, field_id: str, value: Any) -> datetime:
        """Update a single field value. Returns updated_at timestamp."""
        ...

    async def set_settings(self, worker_id: str, values: dict[str, Any]) -> datetime:
        """Replace all settings values. Returns updated_at timestamp."""
        ...
